### ISSUE TITLE
Ventajas y Desventajas

### ISSUE THREAD

**Issue by Alain2701** [Alain2701/Proyecto-Integrador#4]

**Comment by paolagc02** [comment]
## Ventajas del sistema operativo iOS

-   **Elevada seguridad**: El sistema operativo iOS siempre ha presumido de su  **eficiencia frente a las ciberamenazas**  externas. Además con, la última actualización el código de seguridad con el sistema típico de 4 dígitos se ha actualizado a 6 dígitos.
-   **Mayor filtro y exclusividad dentro del mercado de aplicaciones**: Todas las apps para iOS atraviesan un proceso de revisión manual por parte del equipo de Apple.  **Este filtro permite un mercado de aplicaciones más cuidado y con un mayor índice de calidad que en la competencia**. Las encontrarás personalizadas para cada idioma y país. Además, iOS permite tener un mayor control sobre las aplicaciones, ya que cada vez que una app quiere hacer algo, tiene que pedirte permiso para ello.
-   **Interfaz intuitiva:** Los dispositivos de iOS focalizan todos sus elementos en la  **mejora de la experiencia de usuario**, con unas opciones muy sencillas de configuración, pocos botones y un menú de navegación que se caracteriza por la intuición.
-   **El asistente personal SIRI se caracteriza por su gran capacidad para la resolución de tareas**  cotidianas con apoyo virtual. Con la última actualización del sistema se ha vuelto un  **40% más rápido y preciso.**
-   **Integración entre software y hardware:** Además, a pesar de tener un modelo antiguo, **Apple te permite la compatibilidad con sistemas operativos anteriores,**  por lo que puedes disfrutar de las novedades más recientes creadas para tu iPhone.
-   **Elevada duración de la baterí**a, claramente superior a los dispositivos Android. Esto redunda en una envidiable autonomía.
-   **Elaboración de los terminales con algunos de los mejores materiales**  del mercado.
-   **La sincronización entre los diversos dispositivos de Apple**  ha sido, desde su creación, una de las principales banderas de la marca de Steve Jobs. Servicios como iTunes, iTouch o iCloud sirven para sincronizar de forma cómoda y sencilla diferentes servicios.

### Desventajas del sistema operativo iOS

-   **Precios mucho más elevados que sus competidores**: Muchos dispositivos de gama media-alta de Android tienen prestaciones similares y unos costes mucho más competitivos que Apple.
-   **Menor personalización, variedad y especialización con respecto a Android:** Con Android puedes elegir entre un sinfín de modelos, de todos los tamaños y precios, y orientados hacia los perfiles de usuario más variados.
-   **Menor flexibilidad:** En Google Play Store existen diversos launchers cuyo objetivo es sustituir la apariencia por defecto que muestran las distintas versiones de Android por una más atractiva con las funcionalidades y opciones más “a la carta” para el usuario.  **Puedes elegir entre diversos widgets para configurar a tu gusto.**
-   **Carece de la libertad de tener un sistema operativo de código abierto**: Los dispositivos Android pueden instalar aplicaciones procedentes de cualquier fuente, ya sea de la tienda oficial o de otras, mientras que tanto los iPhone como el resto de dispositivos pertenecientes a Apple se encuentran con la  **limitación de hallarse obligados a utilizar únicamente las aplicaciones de la App Store.**
-   **La comunidad de usuarios de Android es la más grande del mundo**, contando con más recursos en línea.

![Resultado de imagen para ventajas y desventajas de IOS](https://parentesis.com/imagesPosts/articles-26090_recurso_jpg.jpg)
